name: main_workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
      - run: make setup
      - run: make lint
      - run: make test